export const constants = {
    DEFAULT_RADIUS: 1,
    MAX_RADIUS: 5,
    MIN_RADIUS: 1,
    METERS_IN_KILOMETER: 1000,
    MAP_ID: "GMAP",
    LOGIN_ROUTE: "/login",
    REGISTER_ROUTE: "/register",
    MAP_ROUTE: "/map",
    USER_COLLECTION: "user",
    LOGIN_FIELD: "login",
    PASSWORD_FIELD: "password",
    BOOKMARK_COLLECTION: "bookmark",
    USER_LOGIN_FIELD: "user_login",
    PLACE_ID_FIELD: "place_id",
    DIGITS_IN_DISTANCE: 1,
};
