export const STYLES = {
    BLUE_COLOR: "#5E7BC7",
    WHITE_COLOR: "white",
    RED_COLOR: "#C75E5E",
    GRAY_COLOR: "#808080",
    ICON_FONT_SIZE: 30,
    BORDER_RADIUS: "border-radius: 10px;",
    BORDER_RADIUS_VALUE: "10px",
    DEFAULT_BORDER: "border: 2px solid #C4C4C4;",
    DEFAULT_BORDER_WIDTH: "2px",
    UNCHECKED_COLOR: "#C4C4C4",
    CHECKED_COLOR: "#333",
    HEADING_FONT_SIZE: "font-size: 24px",
    HEADING_FONT_SIZE_VALUE: "24px",
    TRANSITION_VALUE: "250ms cubic-bezier(0.4, 0, 0.2, 1)",
};
